#!/usr/bin/env python3
"""Generate the compiled MMAT ParamBuffer catalog from DXBC reflection JSONL."""

from __future__ import annotations

import argparse
import collections
import json
import pathlib


SOURCES = (
    (1, 48, "ps/model/foward/ps_characterconstant.pso"),
    (2, 48, "ps/model/foward/lookdev/ps_charactereyelookdev.pso"),
    (3, 96, "ps/model/foward/lookdev/ps_characterfacelookdev.pso"),
    (4, 48, "ps/model/foward/lookdev/ps_characterhairlookdev.pso"),
    (5, 96, "ps/model/foward/lookdev/ps_charactermetallookdev.pso"),
    (6, 48, "ps/model/foward/lookdev/ps_characterskinlookdev.pso"),
    (7, 112, "ps/model/foward/lookdev/ps_elementallookdev.pso"),
    (8, 160, "ps/model/ps_flowmap.pso"),
    (10, 224, "ps/model/ps_glowingground.pso"),
    (11, 336, "ps/model/ps_glowingmountain.pso"),
    (12, 160, "ps/model/ps_ice_1dither_2emissive_3cameraalpha.pso"),
    (13, 224, "ps/model/ps_ice_2layer.pso"),
    (14, 352, "ps/model/ps_lavafall.pso"),
    (15, 112, "ps/model/foward/lookdev/ps_lucilius.pso"),
    (17, 16, "vs/model/vs_plantbillboard.vso"),
    (18, 208, "ps/model/ps_plantmiddleview.pso"),
    (19, 128, "ps/model/ps_plantshake.pso"),
    (20, 128, "ps/model/ps_skycloud.pso"),
    (21, 320, "ps/model/ps_uberenv.pso"),
    (22, 368, "ps/model/ps_uberenv_layer2.pso"),
    (23, 192, "ps/model/ps_uberenv_layer2_plantpivotpainter.pso"),
    (24, 416, "ps/model/ps_uberenv_layer3.pso"),
    (25, 384, "ps/model/ps_uberenv_layer4.pso"),
    (26, 192, "ps/model/ps_uberenv_plantpivotpainter.pso"),
    (27, 64, "ps/model/ps_uberenvtextureless.pso"),
    (28, 368, "ps/model/ps_water_lake.pso"),
    (29, 48, "ps/model/ps_grid.pso"),
)

BINDING_EVIDENCE = {
    1: "C: full-sample size and value contract",
    17: "C: shader family and full-sample size contract",
}
DEFAULT_BINDING_EVIDENCE = "C: shader family and full-sample size contract"


def cpp_type(type_name: str) -> str:
    if type_name.startswith("float"):
        return "FieldType::floating"
    if type_name == "bool":
        return "FieldType::boolean"
    if type_name == "int":
        return "FieldType::signed_integer"
    if type_name in {"uint", "dword"}:
        return "FieldType::unsigned_integer"
    raise ValueError(f"unsupported RDEF field type {type_name!r}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reflection", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--materials", type=pathlib.Path,
                        help="Optional analyze_mmat.py JSONL used to verify first-buffer coverage")
    parser.add_argument("--coverage-output", type=pathlib.Path,
                        help="Optional JSON report for full-material first-buffer coverage")
    args = parser.parse_args()
    if args.coverage_output and not args.materials:
        parser.error("--coverage-output requires --materials")

    wanted = {path for _, _, path in SOURCES}
    shaders = {}
    with args.reflection.open("r", encoding="utf-8") as stream:
        for line in stream:
            shader = json.loads(line)
            if shader.get("file") in wanted:
                shaders[shader["file"]] = shader

    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/research/generate_mmat_cbuffer_catalog.py from DXBC RDEF.",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <span>",
        "",
        "namespace gbfr::editor::mmat_catalog {",
        "enum class FieldType { floating, boolean, signed_integer, unsigned_integer };",
        "struct Field { const char* name; std::uint16_t offset; std::uint16_t size; FieldType type; };",
        "struct Layout { std::uint8_t shader_type; const char* shader; std::uint16_t size; std::span<const Field> fields; const char* binding_evidence; };",
        "",
    ]
    layouts = []
    for shader_type, expected_size, path in SOURCES:
        shader = shaders.get(path)
        if not shader:
            raise ValueError(f"reflection is missing {path}")
        buffers = [item for item in shader.get("constant_buffers", [])
                   if item.get("name") == "ParamBuffer" and item.get("size") == expected_size]
        if len(buffers) != 1:
            raise ValueError(f"{path} has {len(buffers)} matching {expected_size}-byte ParamBuffer entries")
        buffer = buffers[0]
        if buffer["size"] != expected_size:
            raise ValueError(f"{path} ParamBuffer is {buffer['size']} bytes, expected {expected_size}")
        variable_name = f"fields_{shader_type}"
        lines.append(f"inline constexpr Field {variable_name}[] = {{")
        for field in buffer.get("variables", []):
            offset = int(field["offset"])
            size = int(field["size"])
            if offset % 4 or size % 4:
                raise ValueError(f"unaligned field {field['name']} in {path}")
            lines.append(f'    {{"{field["name"]}", {offset}, {size}, {cpp_type(field["type"]["name"])} }},')
        lines.append("};")
        lines.append("")
        layouts.append((shader_type, path, expected_size, variable_name,
                        BINDING_EVIDENCE.get(shader_type, DEFAULT_BINDING_EVIDENCE)))

    lines.append("inline constexpr Layout layouts[] = {")
    for shader_type, path, size, variable_name, binding_evidence in layouts:
        lines.append(
            f'    {{{shader_type}, "{path}", {size}, std::span<const Field>{{{variable_name}}}, '
            f'"{binding_evidence}"}},'
        )
    lines.extend([
        "};",
        "",
        "inline const Layout* find(std::uint8_t shader_type) noexcept {",
        "    for (const auto& layout : layouts) if (layout.shader_type == shader_type) return &layout;",
        "    return nullptr;",
        "}",
        "} // namespace gbfr::editor::mmat_catalog",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    coverage = ""
    if args.materials:
        expected_by_type = {shader_type: size for shader_type, size, _ in SOURCES}
        total = matched = buffer_bearing = no_first_buffer = 0
        mismatch_count = 0
        mismatches = []
        unsupported: collections.Counter[int] = collections.Counter()
        unsupported_samples: dict[int, str] = {}
        per_type: dict[int, collections.Counter[str]] = {}
        with args.materials.open("r", encoding="utf-8") as stream:
            for line in stream:
                material = json.loads(line)
                total += 1
                shader_type = int(material["shader"].split("/", 1)[0])
                stats = per_type.setdefault(shader_type, collections.Counter())
                stats["materials"] += 1
                indices = material.get("buffer_indices", [])
                if not indices:
                    no_first_buffer += 1
                    stats["no_first_buffer"] += 1
                    continue
                buffers = material.get("buffers", [])
                index = int(indices[0])
                actual = len(buffers[index]["words"]) * 4 if 0 <= index < len(buffers) else -1
                if actual < 0:
                    mismatch_count += 1
                    if len(mismatches) < 12:
                        mismatches.append(
                            f"{material['file']}#{material['material']} type={shader_type} "
                            f"has invalid first buffer index {index} for {len(buffers)} buffers"
                        )
                    continue
                buffer_bearing += 1
                stats["buffer_bearing"] += 1
                expected = expected_by_type.get(shader_type)
                if expected is None:
                    unsupported[shader_type] += 1
                    unsupported_samples.setdefault(
                        shader_type, f"{material['file']}#{material['material']} size={actual}"
                    )
                    continue
                if actual == expected:
                    matched += 1
                    stats["matched"] += 1
                else:
                    mismatch_count += 1
                    if len(mismatches) < 12:
                        mismatches.append(f"{material['file']}#{material['material']} type={shader_type} expected={expected} actual={actual}")
        if unsupported:
            details = [
                f"type={shader_type} materials={count} sample={unsupported_samples[shader_type]}"
                for shader_type, count in sorted(unsupported.items())
            ]
            raise ValueError("buffer-bearing shader types missing from catalog:\n" + "\n".join(details))
        if mismatch_count:
            raise ValueError(
                f"material ParamBuffer mismatches ({mismatch_count} total, first {len(mismatches)}):\n"
                + "\n".join(mismatches)
            )
        if matched != buffer_bearing:
            raise ValueError(f"coverage invariant failed: matched={matched} buffer_bearing={buffer_bearing}")
        report = {
            "materials": total,
            "buffer_bearing_materials": buffer_bearing,
            "matched_materials": matched,
            "no_first_buffer_materials": no_first_buffer,
            "buffer_bearing_coverage_percent": round(100.0 * matched / max(1, buffer_bearing), 6),
            "all_material_coverage_percent": round(100.0 * matched / max(1, total), 6),
            "shader_types": [
                {
                    "shader_type": shader_type,
                    "materials": stats["materials"],
                    "buffer_bearing": stats["buffer_bearing"],
                    "matched": stats["matched"],
                    "no_first_buffer": stats["no_first_buffer"],
                    "catalog_size": expected_by_type.get(shader_type),
                }
                for shader_type, stats in sorted(per_type.items())
            ],
        }
        if args.coverage_output:
            args.coverage_output.parent.mkdir(parents=True, exist_ok=True)
            args.coverage_output.write_text(
                json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        coverage = (
            f" matched_materials={matched}/{total} ({100.0 * matched / max(1, total):.2f}%)"
            f" buffer_bearing={matched}/{buffer_bearing}"
            f" no_first_buffer={no_first_buffer}"
        )
    print(f"layouts={len(layouts)}{coverage} output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
